const movieCreateFields = [
    {
        labelText: "Quote",
        labelFor: "quote",
        id: "quote",
        name: "quote",
        type: "quote",
        autoComplete: "quote",
        isRequired: true,
        placeholder: "Please add your quote",
        css: "rounded-md appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-purple-500 focus:border-purple-500 focus:z-10 sm:text-sm",
    },
    {
        labelText: "Movie",
        labelFor: "movie",
        id: "movie",
        name: "movie",
        type: "movie",
        autoComplete: "movie",
        isRequired: true,
        placeholder: "Please add your movie",
        css: "rounded-md appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-purple-500 focus:border-purple-500 focus:z-10 sm:text-sm",
    },
    {
        labelText: "Year",
        labelFor: "year",
        id: "year",
        name: "year",
        type: "year",
        autoComplete: "year",
        isRequired: true,
        placeholder: "What year did the movie come out?",
        css: "rounded-md appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-purple-500 focus:border-purple-500 focus:z-10 sm:text-sm",
    },
    {
        labelText: "Image",
        labelFor: "image_url",
        id: "image_url",
        name: "image_url",
        type: "image_url",
        autoComplete: "image_url",
        isRequired: true,
        placeholder: "Please add an image",
        css: "rounded-md appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-purple-500 focus:border-purple-500 focus:z-10 sm:text-sm",
    },
    {
        labelText: "Rating",
        labelFor: "rating",
        id: "rating",
        name: "rating",
        type: "rating",
        autoComplete: "rating",
        isRequired: true,
        placeholder: "Please add your rating",
        css: "rounded-md appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-purple-500 focus:border-purple-500 focus:z-10 sm:text-sm",
    },
    {
        labelText: "Character",
        labelFor: "character",
        id: "character",
        name: "character",
        type: "character",
        autoComplete: "character",
        isRequired: true,
        placeholder: "Character who said the quote",
        css: "rounded-md appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-purple-500 focus:border-purple-500 focus:z-10 sm:text-sm",
    },
]