const movieCreateFields = [
    {
        labelText: "Quote",
        labelFor: "quote",
        id: "quote",
        name: "quote",
        type: "text",
        autoComplete: "quote",
        isRequired: true,
        placeholder: "Please add your quote",
        css: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white",
    },
    {
        labelText: "Movie",
        labelFor: "movie",
        id: "movie",
        name: "movie",
        type: "text",
        autoComplete: "movie",
        isRequired: true,
        placeholder: "Please add your movie",
        css: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white",
    },
    {
        labelText: "Year",
        labelFor: "year",
        id: "year",
        name: "year",
        type: "text",
        autoComplete: "year",
        isRequired: true,
        placeholder: "What year did the movie come out?",
        css: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white",
    },
    {
        labelText: "Image",
        labelFor: "image_url",
        id: "image_url",
        name: "image_url",
        smallText: "You can grab the image url from wiki",
        type: "text",
        autoComplete: "image_url",
        isRequired: true,
        placeholder: "Please add an image url link",
        css: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white",
    },
    {
        labelText: "Character",
        labelFor: "character",
        id: "character",
        name: "character",
        type: "text",
        autoComplete: "character",
        isRequired: true,
        placeholder: "Character who said the quote",
        css: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white",
    },
];

export { movieCreateFields };
